### ISSUE TITLE
Collaborate in one fork

### ISSUE THREAD

**Issue by davidak** [SartoxOnlyGNU/audacium#3] opened 2021-07-05 18:14 UTC
There is one popular fork that is maintained, but looks for collaborators:

https://github.com/cookiengineer/audacity
https://fosspost.org/audacity-fork-needs-help/

I suggest you archive this repo, add a link to that fork and contribute there. It does not make sense to maintain multiple forks with the same goal.

Thanks for your efforts defending free software!

**Comment by realseb1g** [comment] 2021-07-05 18:19
it's always good to have more forks as well so in case one gets abandoned we have more

**Comment by EchedeyLR** [comment] 2021-07-05 18:20
The problem with that fork if being hosted in a personal repository which is also the main dev.

I would support this fork Instead.

**Comment by davidak** [comment] 2021-07-05 18:31
>it's always good to have more forks as well so in case one gets abandoned we have more

if there is a problem with a fork, it can be forked again. it does not make sense to split up the effort to create a good audio editor and limit the potential

>The problem with that fork if being hosted in a personal repository which is also from the main and only dev.

that makes sense. please collaborate and figure it out together

**Comment by EchedeyLR** [comment] 2021-07-05 18:33
Sorry, but the way you came here was like "we did it first, we won".

Instead of giving an ultimatum I would have suggested only to speak between both sides and that is all.

**Comment by davidak** [comment] 2021-07-05 18:42
my only point is that the other fork is more popular (github stars), so it would make sense to build on that. i'm not part of it, just a user following the mess at audacity

this fork seem to have actually done more commits already, that speak for the maintainers

it does not make sense to have 2 active forks that every linux distro has to package. we can't afford this overhead

please collaborate and figure out what to do best.

sorry if the tone was not perfect

**Comment by trumad** [comment] 2021-07-05 21:50
Given that the other fork is veering towards calling it "sneedacity", I'm gonna keep an eye on this repo also and hope that it takes a better path.

**Comment by CHJ85** [comment] 2021-07-05 23:14
I agree that the other fork should merge in with this one.
Correct me if I'm wrong (and no offense), but it seems that the dev behind this fork has a more constructive goal behind the project.
He even branded it with a name, logo and everything. The other project is still trying to come up with a name.
Both projects are essentially aiming towards the same goal. So why split the devs into two groups?

**Comment by GeekyGami** [comment] 2021-07-06 02:44
I also believe the other fork should be merged with this one or fall to the wayside.
This seems overall a lot cleaner, and handled a lot more seriously, and a lot more for the benefit of the program, than as some sort of PR stunt.

Let's wait and see, maybe SneedCity will be adopted first, who knows.

**Comment by cx405** [comment] 2021-07-06 10:06
From user standpoint, it is irrelevant. Its only relevant from politics standpoint. User is only interested in the software not crashing and working well,.. basically as a reliable tool. And not spying ofc. How it is called, whom it belongs, how forked it is and why, for end user is irrelevant. Best.

**Comment by majestrate** [comment] 2021-07-06 12:47
that other fork's lead seems to have an improper temperament for a project lead of a contentious fork of a widely used software product. i think i would be more likely to contribute to this fork if it continues to devolve into madness over there.

**Comment by alienbob** [comment] 2021-07-06 19:22
As a Slackware distro packager I am more inclined to follow Audacium than that other fork. I don't believe in "more popular fork" just because of a couple of stars. I believe in dedication and quality of work and I see that Sartox has the better papers.

**Comment by AnErrupTion** [comment] 2021-07-06 20:14
I just doubt I'll be able to keep it up as the only person working on this, while the others will be much, much more.

**Comment by riina** [comment] 2021-07-06 20:30
Maybe it's an inordinate amount of work to just keep merging significant patches from upstream / PRs from the multiple people already expressing interest in this fork, but the point is there's already interest in this, so *you're not alone* (more collaborator positions?) and the scale thing doesn't necessarily mean anything, people just use what they want to use, and I think it's worth riding it out until interest might end up drying up.

**Comment by grubeli** [comment] 2021-07-06 21:03
Migrate to: https://github.com/tenacityteam/tenacity

**Comment by AnErrupTion** [comment] 2021-07-06 21:04
> Migrate to: https://github.com/tenacityteam/tenacity

No, I'm keeping my fork.

**Comment by dontfwiththestream** [comment] 2021-07-06 22:01
tenacity is ran by a guy who doesn't program in audacity's languages, and appears to also be a bit unstable

**Comment by AnErrupTion** [comment] 2021-07-06 22:47
To be honest I'm still learning C/C++ but Audacity is giving me the opportunity to learn faster.

**Comment by Remzi1993** [comment] 2021-07-07 07:32
@AnErrupTion please close this issue for archival purposes. It's a strange issue and has nothing to do with the development of this fork.

Before doing so, I would like to point everyone out that I rescinded my support for the other project you all are referring to because of a lack of transparency, issues suddenly get deleted (very important ones like branding vote issue) and I couldn't put my trust in them anymore.

I have written the following statement there, which I expect to be deleted there:

I'm very sorry in advance that I need to write this, but I want to get this off my chest.

I was following this project for a while, without being too active within it because I don't know the programming languages (yet) and I'm a web developer, but what I seem to see a lot is deletion of issues instead of closing them for archival purposes. Closing issues breaths transparency and let others verify results and whatnot.

The last straw for me personally is the sudden deletion of the issue: Project Re-branding/Re-naming due to Trademark Issues (#5)

I wanted to see which naming "won" because I was counting the vote (I just got up this morning) and now I couldn't verify anything, because to me AudioBakery had the most votes. But now nobody can't verify anything. This is for me another red flag that the team who is managing this repo is either unfamiliar how huge open source projects are run or might be forcing their will upon the project either case I'm done, will unstar this project and rescind my personal support. I can't support a project without trust.

Trust is a two way street, a dialogue not a monologue. Duo to this I will be looking for another fork to follow and maybe in the future support. This other fork seems to be reasonable: https://github.com/SartoxOnlyGNU/audacium

My apologies and I wish you guys the best.

**Comment by PlavorSeol** [comment] 2021-07-07 08:12
You are not entitled to demand the maintainer of this fork to kill it and put their effort only to specific fork. Period.

**Comment by PlavorSeol** [comment] 2021-07-07 08:24
Note that this user also spammed [an issue](https://github.com/henricj/audacity/issues/5) on another repository with almost same content.

**Comment by majestrate** [comment] 2021-07-07 09:03
> tenacity is ran by a guy who doesn't program in audacity's languages, and appears to also be a bit unstable

the understatement of the century.

**Comment by majestrate** [comment] 2021-07-07 09:04
this issue is off topic and should be closed.

**Comment by CHJ85** [comment] 2021-07-07 10:21
@majestrate It's not really off-topic.
People are simply pointing out reasons as to why a collab is out of the question. 😀
Audacium sure could use the same amount of traffic and attention though.
Let's just keep em separated for now and see what happens.

**Closed** 2021-07-07 10:25 UTC

**Comment by trumad** [comment] 2021-07-07 11:00
> Audacium sure could need the same amount of traffic and attention though

I thought that, but I've changed my mind. The main guy on Tenacity was allegedly stabbed by a 4channer who didn't like the name. You don't want that kind of attention. Hopefully Audacium continues quietly making improvements and slowly becomes the goto foss audio editor.

**Comment by Narice** [comment] 2021-07-07 11:49
I'm pretty sure this fork will be very good, for now it is a smart move to keep this seperate and grow it gradually. When it is time and the situation cooled of, merging with other groups will be the best move, but for now it wouldn't be smart. 

Also, please @AnErrupTion, remember to not associate with the sneedacity fork as they are related to the harassment of tenacity's ex maintainer
Please read this for more information:
https://github.com/tenacityteam/tenacity/issues/99
As said by @trumad, 4chan harrassed very severely the ex-maintainer in real life.
Do not associate with them.

**Comment by CHJ85** [comment] 2021-07-07 14:40
@Narice When did this happen?
Yesterday he made up some crazy story about how he haven't slept for 2 days because people are harassing him over this fork, which makes no sense as the fork was made 2 days ago right after Muse Group decided to turn Audacity into spyware. The guy is a sympathy seeking drama queen. I wouldn't trust a word from him.

**Comment by Remzi1993** [comment] 2021-07-07 15:30
> I'm pretty sure this fork will be very good, for now it is a smart move to keep this seperate and grow it gradually. When it is time and the situation cooled of, merging with other groups will be the best move, but for now it wouldn't be smart.
> 
> Also, please @AnErrupTion, remember to not associate with the sneedacity fork as they are related to the harassment of tenacity's ex maintainer
> Please read this for more information:
> [tenacityteam/tenacity#99](https://github.com/tenacityteam/tenacity/issues/99)
> As said by @trumad, 4chan harrassed very severely the ex-maintainer in real life.
> Do not associate with them.

Could be true, I have been watching from the sidelines, but I wouldn't assume anything yet. Drama and conflict always has two sides of a story. We just heard one side of it.

I mean, how the ex- maintainer handled some things were (how would I phrase it diplomatically) unexperienced. I would have handled some things differently. Since I have a little bit of experience myself, because I have maintained small open source projects in the past.

**Comment by Narice** [comment] 2021-07-08 10:57
> Could be true, I have been watching from the sidelines, but I wouldn't assume anything yet. Drama and conflict always has two sides of a story. We just heard one side of it.

That is right @Remzi1993, we only heared one side of the story, however, it's a mob versus a single guy so we will probably only hear the side of the single guy (as a mob is a group), and anyway I'm pretty sure no 4channers were hurt during the process.

> I mean, how the ex- maintainer handled some things were (how would I phrase it diplomatically) unexperienced.

I don't really know what you are exactly talking about, are you referring to the deletion of some GitHub issues? I'm pretty sure all deleted issues were in relation to the public poll that they wanted to do for the name, but that went very poorly (they tried twice).
A very good explanation can be found on this issue (which you are the author): https://github.com/tenacityteam/tenacity/issues/121
They were probably in panic mode at the time (cookiengineer was not the sole actor or did not participate in this as he was not even involved in the private poll for the name). The best solution would have probably been to close, lock and put an explanation message instead of closing the GitHub issues, but they probably didn't have time to think it through and to come up with this solution. Closing the spammed issues seems to me like a reasonable solution.

**Comment by Remzi1993** [comment] 2021-07-10 14:40
> > Could be true, I have been watching from the sidelines, but I wouldn't assume anything yet. Drama and conflict always has two sides of a story. We just heard one side of it.
> 
> That is right @Remzi1993, we only heared one side of the story, however, it's a mob versus a single guy so we will probably only hear the side of the single guy (as a mob is a group), and anyway I'm pretty sure no 4channers were hurt during the process.
> 
> > I mean, how the ex- maintainer handled some things were (how would I phrase it diplomatically) unexperienced.
> 
> I don't really know what you are exactly talking about, are you referring to the deletion of some GitHub issues? I'm pretty sure all deleted issues were in relation to the public poll that they wanted to do for the name, but that went very poorly (they tried twice).
> A very good explanation can be found on this issue (which you are the author): [tenacityteam/tenacity#121](https://github.com/tenacityteam/tenacity/issues/121)
> They were probably in panic mode at the time (cookiengineer was not the sole actor or did not participate in this as he was not even involved in the private poll for the name). The best solution would have probably been to close, lock and put an explanation message instead of closing the GitHub issues, but they probably didn't have time to think it through and to come up with this solution. Closing the spammed issues seems to me like a reasonable solution.

I don't want to go in depth why I think and see people (not only the core maintainer) who don't have experience with handeling an open source project, because it's in the past and I already pointed them out in the issue you're referring to.

As I said in that issue, deleting issues is not done and only ever done if the issue is totally spam. I never ever saw any project delete issues before this project. Almost always they were closed. But this is not the only thing which show to me they are not experienced in handeling a project like this. I don't want to point them all out, because what's done is done and I don't want to put any energy in this. I'm only responding to this closed issue as a courtesy - I don't like to keep people hanging.
